import type { Ticket } from '@/types';

// Demo için ODTÜ Teknokent / Mahall civarına dağılmış örnek ticket'lar.
// Hackathon sırasında seed data Supabase'e yüklendiğinde bu dosya silinebilir.
export const SAMPLE_TICKETS: Ticket[] = [
  {
    id: 'sample-1',
    created_by: 'seed',
    location: { latitude: 39.8759, longitude: 32.7551 },
    issue_type: 'missing_ramp',
    severity: 'high',
    affected_users: ['wheelchair', 'stroller'],
    description_tr: 'Teknokent A blok girişinde tekerlekli sandalye rampası eksik.',
    photo_urls: [],
    confidence: 0.92,
    source: 'osm_seed',
    verification_count: 4,
    verified: true,
    status: 'open',
    created_at: '2026-05-12T09:14:00Z',
    updated_at: '2026-05-15T16:02:00Z',
  },
  {
    id: 'sample-2',
    created_by: 'seed',
    location: { latitude: 39.8748, longitude: 32.7472 },
    issue_type: 'pothole',
    severity: 'medium',
    affected_users: ['wheelchair', 'stroller', 'elderly'],
    description_tr: 'Mahall Maidan AVM önünde kaldırımda derin çukur.',
    photo_urls: [],
    confidence: 0.81,
    source: 'mapillary_seed',
    verification_count: 2,
    verified: false,
    status: 'open',
    created_at: '2026-05-13T18:30:00Z',
    updated_at: '2026-05-14T11:10:00Z',
  },
  {
    id: 'sample-3',
    location: { latitude: 39.8771, longitude: 32.7588 },
    created_by: 'seed',
    issue_type: 'missing_tactile_paving',
    severity: 'high',
    affected_users: ['visually_impaired'],
    description_tr: 'Teknokent caddesi yaya geçidinde sarı dokunsal yüzey yok.',
    photo_urls: [],
    confidence: 0.88,
    source: 'user_volunteer',
    verification_count: 5,
    verified: true,
    status: 'in_progress',
    created_at: '2026-05-10T12:00:00Z',
    updated_at: '2026-05-15T09:00:00Z',
  },
  {
    id: 'sample-4',
    location: { latitude: 39.8782, longitude: 32.7501 },
    created_by: 'seed',
    issue_type: 'uneven_surface',
    severity: 'low',
    affected_users: ['elderly', 'wheelchair'],
    description_tr: 'Mahall — Teknokent arası yolda kaldırım dalgalanması.',
    photo_urls: [],
    confidence: 0.7,
    source: 'osm_seed',
    verification_count: 1,
    verified: false,
    status: 'open',
    created_at: '2026-05-15T08:45:00Z',
    updated_at: '2026-05-15T08:45:00Z',
  },
  {
    id: 'sample-5',
    location: { latitude: 39.8744, longitude: 32.7523 },
    created_by: 'seed',
    issue_type: 'obstacle',
    severity: 'medium',
    affected_users: ['visually_impaired', 'wheelchair'],
    description_tr: 'Kaldırıma park edilmiş motorsiklet beyaz baston için engel.',
    photo_urls: [],
    confidence: 0.76,
    source: 'user_volunteer',
    verification_count: 3,
    verified: true,
    status: 'open',
    created_at: '2026-05-14T20:15:00Z',
    updated_at: '2026-05-15T07:20:00Z',
  },
];
