import type { Ticket } from '@/types';

// Demo için ODTÜ Teknokent / Mahall civarına dağılmış örnek ticket'lar.
// Hackathon sırasında seed data Supabase'e yüklendiğinde bu dosya silinebilir.
export const SAMPLE_TICKETS: Ticket[] = [
  {
    id: 'sample-1',
    created_by: 'seed',
    location: { latitude: 39.8759, longitude: 32.7551 },
    issue_type: 'missing_ramp',
    severity: 'high',
    affected_users: ['wheelchair', 'stroller'],
    description_tr: 'Teknokent A blok girişinde tekerlekli sandalye rampası eksik.',
    photo_urls: [],
    confidence: 0.92,
    source: 'osm_seed',
    verification_count: 4,
    verified: true,
    status: 'open',
    created_at: '2026-05-12T09:14:00Z',
    updated_at: '2026-05-15T16:02:00Z',
  },
  {
    id: 'sample-2',
    created_by: 'seed',
    location: { latitude: 39.8748, longitude: 32.7472 },
    issue_type: 'pothole',
    severity: 'medium',
    affected_users: ['wheelchair', 'stroller', 'elderly'],
    description_tr: 'Mahall Maidan AVM önünde kaldırımda derin çukur.',
    photo_urls: [],
    confidence: 0.81,
    source: 'mapillary_seed',
    verification_count: 2,
    verified: false,
    status: 'open',
    created_at: '2026-05-13T18:30:00Z',
    updated_at: '2026-05-14T11:10:00Z',
  },
  {
    id: 'sample-3',
    location: { latitude: 39.8771, longitude: 32.7588 },
    created_by: 'seed',
    issue_type: 'missing_tactile_paving',
    severity: 'high',
    affected_users: ['visually_impaired'],
    description_tr: 'Teknokent caddesi yaya geçidinde sarı dokunsal yüzey yok.',
    photo_urls: [],
    confidence: 0.88,
    source: 'user_volunteer',
    verification_count: 5,
    verified: true,
    status: 'in_progress',
    created_at: '2026-05-10T12:00:00Z',
    updated_at: '2026-05-15T09:00:00Z',
  },
  {
    id: 'sample-4',
    location: { latitude: 39.8782, longitude: 32.7501 },
    created_by: 'seed',
    issue_type: 'uneven_surface',
    severity: 'low',
    affected_users: ['elderly', 'wheelchair'],
    description_tr: 'Mahall — Teknokent arası yolda kaldırım dalgalanması.',
    photo_urls: [],
    confidence: 0.7,
    source: 'osm_seed',
    verification_count: 1,
    verified: false,
    status: 'open',
    created_at: '2026-05-15T08:45:00Z',
    updated_at: '2026-05-15T08:45:00Z',
  },
  {
    id: 'sample-5',
    location: { latitude: 39.8744, longitude: 32.7523 },
    created_by: 'seed',
    issue_type: 'obstacle',
    severity: 'medium',
    affected_users: ['visually_impaired', 'wheelchair'],
    description_tr: 'Kaldırıma park edilmiş motorsiklet beyaz baston için engel.',
    photo_urls: [],
    confidence: 0.76,
    source: 'user_volunteer',
    verification_count: 3,
    verified: true,
    status: 'open',
    created_at: '2026-05-14T20:15:00Z',
    updated_at: '2026-05-15T07:20:00Z',
  },
  {
    id: 'sample-6',
    created_by: 'seed',
    location: { latitude: 39.8767, longitude: 32.7543 },
    issue_type: 'narrow_passage',
    severity: 'medium',
    affected_users: ['wheelchair', 'stroller'],
    description_tr: 'Teknokent otopark çıkışında reklam panosu geçiş genişliğini daraltıyor.',
    photo_urls: [],
    confidence: 0.79,
    source: 'mapillary_seed',
    verification_count: 2,
    verified: false,
    status: 'open',
    created_at: '2026-05-12T13:22:00Z',
    updated_at: '2026-05-16T08:40:00Z',
  },
  {
    id: 'sample-7',
    created_by: 'seed',
    location: { latitude: 39.8791, longitude: 32.7569 },
    issue_type: 'water_pooling',
    severity: 'low',
    affected_users: ['elderly', 'wheelchair'],
    description_tr: 'Durak önündeki eğim bozuk olduğu için yağmur sonrası su birikiyor.',
    photo_urls: [],
    confidence: 0.67,
    source: 'osm_seed',
    verification_count: 1,
    verified: false,
    status: 'open',
    created_at: '2026-05-11T07:55:00Z',
    updated_at: '2026-05-14T15:30:00Z',
  },
  {
    id: 'sample-8',
    created_by: 'seed',
    location: { latitude: 39.8729, longitude: 32.7494 },
    issue_type: 'damaged_equipment',
    severity: 'high',
    affected_users: ['visually_impaired', 'elderly'],
    description_tr: 'Sesli yaya butonu çalışmıyor, kavşakta yön bilgisi alınamıyor.',
    photo_urls: [],
    confidence: 0.86,
    source: 'user_volunteer',
    verification_count: 4,
    verified: true,
    status: 'in_progress',
    created_at: '2026-05-09T16:18:00Z',
    updated_at: '2026-05-16T10:12:00Z',
  },
  {
    id: 'sample-9',
    created_by: 'seed',
    location: { latitude: 39.8804, longitude: 32.7606 },
    issue_type: 'missing_tactile_paving',
    severity: 'medium',
    affected_users: ['visually_impaired'],
    description_tr: 'Yaya adasında dokunsal yüzey kesintiye uğruyor.',
    photo_urls: [],
    confidence: 0.83,
    source: 'mapillary_seed',
    verification_count: 3,
    verified: true,
    status: 'open',
    created_at: '2026-05-13T10:05:00Z',
    updated_at: '2026-05-15T18:44:00Z',
  },
  {
    id: 'sample-10',
    created_by: 'seed',
    location: { latitude: 39.8738, longitude: 32.7597 },
    issue_type: 'obstacle',
    severity: 'high',
    affected_users: ['wheelchair', 'visually_impaired', 'stroller'],
    description_tr: 'Kaldırım ortasında açık bırakılmış elektrik kutusu var.',
    photo_urls: [],
    confidence: 0.91,
    source: 'user_volunteer',
    verification_count: 6,
    verified: true,
    status: 'open',
    created_at: '2026-05-16T06:48:00Z',
    updated_at: '2026-05-16T12:25:00Z',
  },
  {
    id: 'sample-11',
    created_by: 'seed',
    location: { latitude: 39.8716, longitude: 32.7527 },
    issue_type: 'uneven_surface',
    severity: 'medium',
    affected_users: ['elderly', 'wheelchair'],
    description_tr: 'Kaldırım taşları yerinden oynamış, baston ve tekerlek takılıyor.',
    photo_urls: [],
    confidence: 0.74,
    source: 'osm_seed',
    verification_count: 2,
    verified: false,
    status: 'open',
    created_at: '2026-05-12T19:40:00Z',
    updated_at: '2026-05-13T09:21:00Z',
  },
  {
    id: 'sample-12',
    created_by: 'seed',
    location: { latitude: 39.8778, longitude: 32.7632 },
    issue_type: 'missing_ramp',
    severity: 'high',
    affected_users: ['wheelchair', 'stroller', 'elderly'],
    description_tr: 'Servis durağına çıkan kaldırımda rampa yok.',
    photo_urls: [],
    confidence: 0.89,
    source: 'mapillary_seed',
    verification_count: 5,
    verified: true,
    status: 'in_progress',
    created_at: '2026-05-10T08:16:00Z',
    updated_at: '2026-05-16T14:50:00Z',
  },
  {
    id: 'sample-13',
    created_by: 'seed',
    location: { latitude: 39.8699, longitude: 32.7478 },
    issue_type: 'pothole',
    severity: 'medium',
    affected_users: ['wheelchair', 'elderly'],
    description_tr: 'Ara sokak girişinde tekerlekli sandalye rotasını kesen çukur var.',
    photo_urls: [],
    confidence: 0.8,
    source: 'ibb_open_data',
    verification_count: 2,
    verified: false,
    status: 'open',
    created_at: '2026-05-14T08:32:00Z',
    updated_at: '2026-05-14T17:03:00Z',
  },
  {
    id: 'sample-14',
    created_by: 'seed',
    location: { latitude: 39.882, longitude: 32.7554 },
    issue_type: 'other',
    severity: 'low',
    affected_users: ['visually_impaired'],
    description_tr: 'Baş hizasına sarkan tabela beyaz bastonla fark edilmiyor.',
    photo_urls: [],
    confidence: 0.64,
    source: 'user_volunteer',
    verification_count: 1,
    verified: false,
    status: 'open',
    created_at: '2026-05-15T12:10:00Z',
    updated_at: '2026-05-15T12:10:00Z',
  },
  {
    id: 'sample-15',
    created_by: 'seed',
    location: { latitude: 39.8752, longitude: 32.7645 },
    issue_type: 'narrow_passage',
    severity: 'high',
    affected_users: ['wheelchair', 'stroller'],
    description_tr: 'Kafe masa ve sandalyeleri kaldırım geçişini tamamen daraltıyor.',
    photo_urls: [],
    confidence: 0.87,
    source: 'mapillary_seed',
    verification_count: 4,
    verified: true,
    status: 'open',
    created_at: '2026-05-13T21:08:00Z',
    updated_at: '2026-05-16T09:35:00Z',
  },
  {
    id: 'sample-16',
    created_by: 'seed',
    location: { latitude: 39.8686, longitude: 32.7536 },
    issue_type: 'missing_tactile_paving',
    severity: 'high',
    affected_users: ['visually_impaired'],
    description_tr: 'Otobüs durağı ile yaya geçidi arasında yönlendirici yüzey yok.',
    photo_urls: [],
    confidence: 0.9,
    source: 'osm_seed',
    verification_count: 3,
    verified: true,
    status: 'open',
    created_at: '2026-05-11T14:28:00Z',
    updated_at: '2026-05-15T13:19:00Z',
  },
  {
    id: 'sample-17',
    created_by: 'seed',
    location: { latitude: 39.8796, longitude: 32.7488 },
    issue_type: 'uneven_surface',
    severity: 'low',
    affected_users: ['elderly', 'stroller'],
    description_tr: 'Ağaç kökü kaldırım yüzeyini kabartmış.',
    photo_urls: [],
    confidence: 0.72,
    source: 'mapillary_seed',
    verification_count: 1,
    verified: false,
    status: 'open',
    created_at: '2026-05-16T11:42:00Z',
    updated_at: '2026-05-16T11:42:00Z',
  },
  {
    id: 'sample-18',
    created_by: 'seed',
    location: { latitude: 39.8722, longitude: 32.762 },
    issue_type: 'water_pooling',
    severity: 'medium',
    affected_users: ['wheelchair', 'stroller', 'elderly'],
    description_tr: 'Alt geçit çıkışında mazgal tıkalı, geçiş alanı su altında kalıyor.',
    photo_urls: [],
    confidence: 0.78,
    source: 'ibb_open_data',
    verification_count: 2,
    verified: false,
    status: 'in_progress',
    created_at: '2026-05-10T17:36:00Z',
    updated_at: '2026-05-16T07:55:00Z',
  },
  {
    id: 'sample-19',
    created_by: 'seed',
    location: { latitude: 39.884, longitude: 32.7609 },
    issue_type: 'obstacle',
    severity: 'medium',
    affected_users: ['visually_impaired', 'wheelchair'],
    description_tr: 'Geri dönüşüm konteyneri kaldırım üstünde sabit engel oluşturuyor.',
    photo_urls: [],
    confidence: 0.77,
    source: 'user_volunteer',
    verification_count: 3,
    verified: true,
    status: 'open',
    created_at: '2026-05-12T11:17:00Z',
    updated_at: '2026-05-16T16:20:00Z',
  },
  {
    id: 'sample-20',
    created_by: 'seed',
    location: { latitude: 39.8669, longitude: 32.7489 },
    issue_type: 'damaged_equipment',
    severity: 'medium',
    affected_users: ['visually_impaired', 'elderly'],
    description_tr: 'Yaya geçidi uyarı lambası kırık ve gece fark edilmiyor.',
    photo_urls: [],
    confidence: 0.75,
    source: 'osm_seed',
    verification_count: 2,
    verified: false,
    status: 'open',
    created_at: '2026-05-13T05:50:00Z',
    updated_at: '2026-05-14T20:02:00Z',
  },
  {
    id: 'sample-21',
    created_by: 'seed',
    location: { latitude: 39.8788, longitude: 32.7531 },
    issue_type: 'pothole',
    severity: 'high',
    affected_users: ['wheelchair', 'stroller', 'elderly'],
    description_tr: 'Servis ring yoluna bağlanan kaldırımda büyük çökme var.',
    photo_urls: [],
    confidence: 0.93,
    source: 'mapillary_seed',
    verification_count: 5,
    verified: true,
    status: 'open',
    created_at: '2026-05-15T15:04:00Z',
    updated_at: '2026-05-16T18:11:00Z',
  },
  {
    id: 'sample-22',
    created_by: 'seed',
    location: { latitude: 39.8708, longitude: 32.7581 },
    issue_type: 'missing_ramp',
    severity: 'medium',
    affected_users: ['wheelchair', 'stroller'],
    description_tr: 'Yaya geçidinin tek tarafında rampa var, karşı kaldırımda yok.',
    photo_urls: [],
    confidence: 0.84,
    source: 'user_volunteer',
    verification_count: 3,
    verified: true,
    status: 'in_progress',
    created_at: '2026-05-09T09:27:00Z',
    updated_at: '2026-05-15T19:42:00Z',
  },
  {
    id: 'sample-23',
    created_by: 'seed',
    location: { latitude: 39.8815, longitude: 32.7468 },
    issue_type: 'other',
    severity: 'low',
    affected_users: ['elderly', 'visually_impaired'],
    description_tr: 'Bank önünde gevşek kapak sallanıyor ve basınca ses yapıyor.',
    photo_urls: [],
    confidence: 0.62,
    source: 'ibb_open_data',
    verification_count: 1,
    verified: false,
    status: 'open',
    created_at: '2026-05-14T13:13:00Z',
    updated_at: '2026-05-14T13:13:00Z',
  },
  {
    id: 'sample-24',
    created_by: 'seed',
    location: { latitude: 39.876, longitude: 32.7498 },
    issue_type: 'obstacle',
    severity: 'medium',
    affected_users: ['wheelchair', 'stroller'],
    description_tr: 'Market sevkiyat rampası kaldırım hattını kapatıyor.',
    photo_urls: [],
    confidence: 0.82,
    source: 'mapillary_seed',
    verification_count: 2,
    verified: false,
    status: 'open',
    created_at: '2026-05-16T09:06:00Z',
    updated_at: '2026-05-16T09:06:00Z',
  },
  {
    id: 'sample-25',
    created_by: 'seed',
    location: { latitude: 39.8831, longitude: 32.7522 },
    issue_type: 'missing_tactile_paving',
    severity: 'medium',
    affected_users: ['visually_impaired'],
    description_tr: 'Site girişinde kılavuz çizgi bina duvarında aniden bitiyor.',
    photo_urls: [],
    confidence: 0.85,
    source: 'user_volunteer',
    verification_count: 3,
    verified: true,
    status: 'open',
    created_at: '2026-05-11T18:05:00Z',
    updated_at: '2026-05-16T15:48:00Z',
  },
];
